# Generated by Django 5.0.10 on 2024-12-19 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_pct', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=100)),
                ('nome_social', models.CharField(blank=True, max_length=100)),
                ('genero', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
                ('estado_civil', models.CharField(max_length=10)),
                ('profissao', models.CharField(max_length=20)),
                ('telefone_principal', models.CharField(max_length=15)),
                ('telefone_secundario', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
                ('data', models.DateField()),
                ('forma_pagamento', models.CharField(blank=True, max_length=20)),
                ('responsavel_financeiro', models.CharField(blank=True, max_length=100)),
                ('observacoes_gerais', models.TextField(blank=True)),
                ('faltas', models.CharField(max_length=3)),
                ('id_pct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conectapsiApp.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_end', models.AutoField(primary_key=True, serialize=False)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('id_pct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conectapsiApp.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Historico_clinico',
            fields=[
                ('id_hc', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_atendimento', models.CharField(blank=True, max_length=50)),
                ('plano_de_saude', models.CharField(blank=True, max_length=50)),
                ('numero_carteirinha', models.CharField(blank=True, max_length=50)),
                ('historico_medico', models.TextField(blank=True)),
                ('historico_familiar', models.TextField(blank=True)),
                ('diagnosticos_preexistentes', models.TextField(blank=True)),
                ('uso_medicamentos', models.TextField(blank=True)),
                ('id_pct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conectapsiApp.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Psicologia',
            fields=[
                ('id_psi', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_consulta', models.TextField(blank=True)),
                ('historico_tratamentos', models.TextField(blank=True)),
                ('principais_sintomas', models.TextField(blank=True)),
                ('observacoes_clinicas', models.TextField(blank=True)),
                ('id_pct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conectapsiApp.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='uploadFile',
            fields=[
                ('id_upfile', models.AutoField(primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='uploads/')),
                ('nome_do_arquivo', models.CharField(max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('tamanho_do_arquivo', models.IntegerField()),
                ('id_pct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conectapsiApp.clientes')),
            ],
        ),
    ]
