# Generated by Django 5.0.10 on 2025-01-22 02:11

import conectapsiApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conectapsiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[conectapsiApp.models.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessaoclinica',
            name='id_pct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_cliente', to='conectapsiApp.clientes'),
        ),
    ]
