# Generated by Django 5.0.10 on 2024-12-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conectapsiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='nome_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='profissao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone_secundario',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='observacoes_gerais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='responsavel_financeiro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historico_clinico',
            name='diagnosticos_preexistentes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historico_clinico',
            name='historico_familiar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historico_clinico',
            name='historico_medico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historico_clinico',
            name='numero_carteirinha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historico_clinico',
            name='plano_de_saude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historico_clinico',
            name='tipo_de_atendimento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historico_clinico',
            name='uso_medicamentos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='historico_tratamentos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='motivo_consulta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='observacoes_clinicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='principais_sintomas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
