# Generated by Django 5.0.10 on 2024-12-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conectapsiApp', '0002_alter_clientes_nome_social_alter_clientes_profissao_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Psicologia',
            new_name='prontuario',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='telefone_secundario',
            new_name='telefone_emergencia',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='observacoes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
