# Generated by Django 5.0.10 on 2025-02-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conectapsiApp', '0002_alter_clientes_cpf_alter_clientes_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='conjuge_profissao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
