# Generated by Django 5.0.10 on 2024-12-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conectapsiApp', '0003_rename_psicologia_prontuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
