# Generated by Django 5.0.10 on 2024-12-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conectapsiApp', '0004_alter_clientes_data_cadastro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='nome_completo',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='clientes',
            name='sobrenome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
