# Generated by Django 5.0.10 on 2024-12-23 23:14

import conectapsiApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conectapsiApp', '0005_rename_nome_completo_clientes_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='conjuge_idade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='conjuge_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='conjuge_sexo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='filhos_idade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='filhos_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='filhos_sexo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='religiao',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='consultas',
            name='valor_pagamento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='evolucao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(max_length=14, validators=[conectapsiApp.models.validar_cpf]),
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id_anamense', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_atendimento', models.CharField(blank=True, max_length=50, null=True)),
                ('plano_de_saude', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_carteirinha', models.CharField(blank=True, max_length=50, null=True)),
                ('historico_medico', models.TextField(blank=True, null=True)),
                ('historico_familiar', models.TextField(blank=True, null=True)),
                ('diagnosticos_preexistentes', models.TextField(blank=True, null=True)),
                ('uso_medicamentos', models.TextField(blank=True, null=True)),
                ('uso_medicamentos_alternativos', models.TextField(blank=True, null=True)),
                ('uso_de_drogas', models.TextField(blank=True, null=True)),
                ('conceituacao_psicologica_do_caso', models.TextField(blank=True, null=True)),
                ('queixa_principal', models.TextField(blank=True, null=True)),
                ('possibilidade_de_horarios', models.TextField(blank=True, null=True)),
                ('fez_terapia_anterior', models.CharField(blank=True, max_length=3, null=True)),
                ('quando_fez_terapia_anterior', models.CharField(blank=True, max_length=15, null=True)),
                ('expectativa_e_objetivo_do_paciente', models.TextField(blank=True, null=True)),
                ('sintomas_apresentados', models.TextField(blank=True, null=True)),
                ('transtornos_psiquiatricos_anteriores', models.TextField(blank=True, null=True)),
                ('transtornos_psiquiatricos_familiares', models.TextField(blank=True, null=True)),
                ('doenca_importante_que_teve', models.TextField(blank=True, null=True)),
                ('aplicacao_de_teste', models.TextField(blank=True, null=True)),
                ('historico_da_queixa_quando_se_iniciou', models.TextField(blank=True, null=True)),
                ('eventos_traumaticos_da_vida', models.TextField(blank=True, null=True)),
                ('eventos_que_agravam_a_crise', models.TextField(blank=True, null=True)),
                ('tentativa_de_suicidio', models.TextField(blank=True, null=True)),
                ('relacionamentos_importantes_mae', models.TextField(blank=True, null=True)),
                ('relacionamentos_importantes_pai', models.TextField(blank=True, null=True)),
                ('relacionamentos_importantes_irmaos', models.TextField(blank=True, null=True)),
                ('relacionamentos_importantes_filhos', models.TextField(blank=True, null=True)),
                ('relacionamentos_importantes_outros', models.TextField(blank=True, null=True)),
                ('observacao_sobre_dinamica_familiar_atual', models.TextField(blank=True, null=True)),
                ('infancia_gravidez_planejada', models.TextField(blank=True, null=True)),
                ('infancia_amamentacao', models.TextField(blank=True, null=True)),
                ('infancia_estressores_crises', models.TextField(blank=True, null=True)),
                ('infancia_transtornos_infantis', models.TextField(blank=True, null=True)),
                ('infancia_comentarios', models.TextField(blank=True, null=True)),
                ('adolescencia_experiencias_afetivas_marcantes', models.TextField(blank=True, null=True)),
                ('adolescencia_experiencias_sexuais_marcantes', models.TextField(blank=True, null=True)),
                ('adolescencia_independencia', models.TextField(blank=True, null=True)),
                ('adolescencia_circulo_de_amizades', models.TextField(blank=True, null=True)),
                ('vida_adulta_relacionamento_com_parceiro', models.TextField(blank=True, null=True)),
                ('vida_adulta_vida_sexual_atual', models.TextField(blank=True, null=True)),
                ('vida_adulta_situacao_financeira', models.TextField(blank=True, null=True)),
                ('vida_adulta_abordo_espontaneo', models.TextField(blank=True, null=True)),
                ('vida_adulta_apoio_social', models.TextField(blank=True, null=True)),
                ('vida_adulta_outros_transtornos', models.TextField(blank=True, null=True)),
                ('vida_adulta_principais_lazeres', models.TextField(blank=True, null=True)),
                ('observacao_e_linguagem_nao_verbal', models.TextField(blank=True, null=True)),
                ('atendimentos_prestados_profissional', models.CharField(blank=True, max_length=100, null=True)),
                ('atendimentos_prestados_encaminhamentos', models.CharField(blank=True, max_length=100, null=True)),
                ('atendimentos_prestados_terapeutica_utilizada', models.CharField(blank=True, max_length=255, null=True)),
                ('atendimentos_prestados_destino_do_caso_alta', models.CharField(blank=True, max_length=4, null=True)),
                ('atendimentos_prestados_destino_do_caso_encaminhamento_outra_instituicao', models.CharField(blank=True, max_length=100, null=True)),
                ('atendimentos_prestados_destino_do_caso_abandono', models.CharField(blank=True, max_length=255, null=True)),
                ('atendimentos_prestados_destino_do_caso_outro_profissional', models.CharField(blank=True, max_length=100, null=True)),
                ('atendimentos_prestados_destino_do_caso_interrompido', models.CharField(blank=True, max_length=255, null=True)),
                ('atendimentos_prestados_destino_do_caso_melhoras_obtidas', models.TextField(blank=True, null=True)),
                ('atendimentos_prestados_destino_do_caso_outras_obs', models.TextField(blank=True, null=True)),
                ('id_pct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conectapsiApp.clientes')),
            ],
        ),
        migrations.DeleteModel(
            name='Historico_clinico',
        ),
    ]
