# Generated by Django 5.0.10 on 2024-12-27 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conectapsiApp', '0006_clientes_conjuge_idade_clientes_conjuge_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='endereco',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cliente_principal', to='conectapsiApp.endereco'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id_pct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='conectapsiApp.clientes'),
        ),
    ]
