# Generated by Django 5.0.10 on 2024-12-27 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conectapsiApp', '0007_clientes_endereco_alter_endereco_id_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='id_pct',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='conectapsiApp.clientes'),
        ),
    ]
