# Generated by Django 5.0.10 on 2024-12-27 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conectapsiApp', '0008_alter_endereco_id_pct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='endereco',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id_pct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='conectapsiApp.clientes'),
        ),
    ]
